### ISSUE TITLE
Remember sessions

### ISSUE THREAD

**Issue by dellitsni** [dellitsni/Konsent#11]
Right now, users are logged out when they close their browser. Logging in every time you open the page gets annoying quickly. We could use cookies to remember users even after they've closed their browser.

**Comment by UnbanTwin** [comment]
I'd be happy to take a crack at this.

**Comment by dellitsni** [comment]
@UnbanTwin Alright, I think this is a good place to start if you want to get to know the codebase and so on. If you need help with anything just let me or one of the others know. Good luck with it!
