### ISSUE TITLE
Make voting onymous

### ISSUE THREAD

**Issue by dellitsni** [dellitsni/Konsent#15]
As pointed out by a Redditor, Konsent is currently vulnerable to vote manipulation by the administrator of the database. To combat this, we should make voting onymous.

**Comment by surrealbytes** [comment]
how does that prevent the admin from manipulating the votes?

**Comment by dellitsni** [comment]
@surrealbytes It won't directly prevent it, but it will make it possible for users to figure out if votes are being manipulated with. 

Vote manipulation from the administrator would become even harder if we tied accounts to Raddle as i explained in #18.
