### ISSUE TITLE
Reset timer if no solution is found in phase 2

### ISSUE THREAD

**Issue by dellitsni** [dellitsni/Konsent#17]
If a solution hasn't been suggested in time, the post shouldn't be marked as solved with the solution being "None". Instead, the timer should reset until a solution is found.

**Comment by surrealbytes** [comment]
maybe expose these timers to the user at some point, the creator of the issue? don't have to rush this.

**Comment by dellitsni** [comment]
@surrealbytes Yeah, we should definitely make it visible to both users and author. Something like "Posted X hours ago, progressing in X hours".

**Comment by surrealbytes** [comment]
i meant to make them configurable by the creator of the issue at some point. Different Unions may want different timers depending on their needs and some issues may require faster iterations than others.

**Comment by dellitsni** [comment]
@surrealbytes Oh, right. That's a good idea. Not necessary at the moment though, but nice to have. A simple optional input when posting new issues should be enough for now. I'll open a new issue for that.

**Comment by dellitsni** [comment]
@surrealbytes How about we make a new label called "important" or something like that, to differentiate between nice to have features and necessary features?

**Comment by surrealbytes** [comment]
choose w/e labels you like and i will follow. have seen too many projects with different approaches to this and imho there is no right way, only your way :)
