### ISSUE TITLE
[updated] Remove display name and enforce better passwords

### ISSUE THREAD

**Issue by dellitsni** [dellitsni/Konsent#18]
As things are now, multiple accounts can exist with the same usernames and/or display names. This results in some strange behavior upon login, and creates general confusion to who is who.

**Comment by surrealbytes** [comment]
having both unique reduces the amount of possible names one can choose. what about having one name as you've mentioned before? are you worried about security if it's only one user identifier?

**Comment by dellitsni** [comment]
@surrealbytes The two names are actually another leftover from the original version of Konsent, designed for physical communities, where people needed to log in using a username but wanted to appear on the site with their real name.

Another user on Raddle suggested yesterday that we make it so that every account in the Raddle union must be tied to a Raddle account. The tie can be confirmed by sending a PM to the Raddle account with a "click to confirm" link. This way, we could make it so that only users with X amount of comments, posts or recieved upvotes can contribute on Konsent, and we can make it much harder for griefers to fuck things up. What do you think about replacing "display name" with Raddle name, and implementing it like this?

**Comment by surrealbytes** [comment]
This way Konsent will be tied with Raddle. with Postmill being dead that won't be good for Konsent. If Postmill had an API this would have been easier. It's a hard topic and not my area of expertise, we can wait for someone to suggest something concrete or do some research by ourselves. In the meantime we can try and keep it simple and follow the [YAGNI](https://en.m.wikipedia.org/wiki/You_aren%27t_gonna_need_it) principle. :)

**Comment by dellitsni** [comment]
@surrealbytes I wouldn't tie Konsent with Raddle, just the Raddle union, as a sort of special feature for that union. But i think you're right that we should keep things simple right now. A Raddle bot can always come later on. I'll delete this from v0.2a, do you think we should close the issue too or leave it open?

**Comment by dellitsni** [comment]
Almost finished with this, see #30.

**Comment by dellitsni** [comment]
Merged #30.
