### ISSUE TITLE
Give each 'phase' a name

### ISSUE THREAD

**Issue by surrealbytes** [dellitsni/Konsent#23]
This will make each phase distinct both from the user
and developer perspective. It would also make it easier
to add new phases without getting lost with 'phase' + integer names.

**Comment by dellitsni** [comment]
Good idea. We could name the phases based on their purpose, or their content. If we named based on purpose, phase one would be called "Filtering" or some synonym. If we named based on content, it would be "Issues", "Problems", "Dilemmas" or something along those lines. We could also use something entirely different. What do you think? @surrealbytes

**Comment by surrealbytes** [comment]
Depends on how abstract we want phases to be. Do we want to be able to easily add/remove phases in later development? Do we want a modular system where users/unions can choose the phases? We should seriously consider the arguments someone made about phase2 being just a majority vote. I should probably open another issue about the decision making paradigm. This also could be part of #3 and the refactor that the app needs.

**Comment by surrealbytes** [comment]
closing in favor of #24 and #3
