### ISSUE TITLE
Better password security

### ISSUE THREAD

**Issue by iodbh** [dellitsni/Konsent#26]
Password security as it is is not suitable for production use : 

- We are using sha256, which is too fast for password hashing (see [this](https://security.stackexchange.com/questions/90064/how-secure-are-sha256-salt-hashes-for-password-storage))
- The hashes are unsalted, which make cracking a breeze

I would recommend switching back to passlib, which implements recommended algorithms and conveniently wraps hashing.

**Comment by surrealbytes** [comment]
I think we should use the `werkzeug` module that comes with Flask, [utils](http://werkzeug.pocoo.org/docs/0.14/utils/#module-werkzeug.security) have some usefull functions.

**Comment by dellitsni** [comment]
There's also `bcrypt`, which looks like a solid choice. Allows us to dictate slowness and salt easily. Hasn't been updated since 2015, though...

**Comment by dellitsni** [comment]
I finally got a new laptop, so if you guys are alright with using `bcrypt`, I'll implement it instead of `hashlib`.

**Comment by dellitsni** [comment]
We're now using `bcrypt`.
