### ISSUE TITLE
Constrain name and password length

### ISSUE THREAD

**Issue by surrealbytes** [dellitsni/Konsent#27]
Tried this with the #25 branch and atm it's sqlalchemy library that does the check and raises an exception, haven't tested with master/develop branches but it must be kinda the same.
Not sure if wtforms can put constraints, i will have to take a look at this cool lib.

**Comment by surrealbytes** [comment]
oops my bad, i see now there is `StringField('Display name', [validators.Length(min=1, max=50)`
i somehwhat got an error from sqlalchemy though, i will try and test more.

**Comment by dellitsni** [comment]
@surrealbytes Yeah, we got this down already. Just let me know when you think #25 is ready for merging.
