### ISSUE TITLE
Fix selenium tests inconsistency

### ISSUE THREAD

**Issue by surrealbytes** [dellitsni/Konsent#28]
The `.click()` method on elements seems to be kinda buggy, if the response takes long
enough selenium doesn't wait and the tests continue and just fail, there seems also to be some lag on loading pages in selenium.

We can either change the `click()` method with `get(url)` that waits until the page is loaded
or use [WebDriverWait](https://seleniumhq.github.io/selenium/docs/api/py/webdriver_support/selenium.webdriver.support.wait.html?highlight=wait#selenium.webdriver.support.wait) but meh..

**Comment by dellitsni** [comment]
Using `get()` means we can't test for broken links, right? Not that links break often, though..

**Comment by iodbh** [comment]
Isn't Selenium a bit overkill considering we have no javascript to run ? A simpler requests-html  client would spare us all the Selenium fuckery

**Comment by surrealbytes** [comment]
Flask has some nice documentation on testing, i will move most of these to unit tests, we can keep a bare minimum as acceptance tests mainly for UI stuff in selenium.

**Comment by surrealbytes** [comment]
i'm getting this in the JS debugger 
`JavaScript error: http://127.0.0.1:5000/static/js/bootstrap.min.js, line 6: TypeError: t is undefined`
not sure if it's a bootstrap error or if anything is missing.

**Comment by iodbh** [comment]
I can't push to github due to bad wifi at the moment, but this is due to bootstrap's JS being included after jquery. Place the jquery `<script>` tag before bootstrap's JS to get rid of the error.

**Comment by dellitsni** [comment]
Fixed it.

**Comment by surrealbytes** [comment]
thank you peeps! i don't expect this to make any difference in selenium though, but we'll see. i've refactored the user story some.
