### ISSUE TITLE
Clean things up

### ISSUE THREAD

**Issue by dellitsni** [dellitsni/Konsent#3]
In its current state, Konsent is somewhat of a mess. Before we do anything big, we should focus on cleaning up the code and making things easier to get into.

**Comment by surrealbytes** [comment]
how would you like to go about doing this? remove anything database related to a different module? also add a `__main__.py` to glue things together and `setup.py` for installation with pip?

**Comment by dellitsni** [comment]
@surrealbytes First of all, there's a lot of things that just aren't well written. I fixed some of the worst issues today, but there's still plenty of room for improvement.

You're right about separating `flask_app.py` into more convenient and organised files. One for routes and one for helper functions would be a good start. A setup script would be nice too, that shouldn't be super difficult and would make it much easier for new users to get things up and running.

I feel like all of this should be new, separate issues, though.

**Comment by surrealbytes** [comment]
btw the app runs perfectly fine on python3 aswell, how about making it python3 only?

**Comment by surrealbytes** [comment]
is there any reason to have `passlib` as a dependency? ?, python has the builtin `hashlib` that can do sha256 hashing aswell, also `passlib` hasn't been updated for more than a year.

**Comment by dellitsni** [comment]
@surrealbytes I suppose we could make it python3 only. Are you sure that it runs without any changes in python3?

Let's replace passlib with hashlib then, hadn't thought about that. Reducing dependencies would be really nice. I'm gonna open a new issue.

**Comment by surrealbytes** [comment]
yeah i've been running konsent on python3 and playing around since yesterday and no problems caused by python version.

**Comment by surrealbytes** [comment]
For cleaning the database stuff and adding support for sqlite, something like [peewee](https://github.com/coleifer/peewee) can be useful. Haven't used it before, but if you've used Django's ORM, it's the same concept.

**Comment by dellitsni** [comment]
@surrealbytes Python3 it is then. I'll add it to the readme.

Never used peewee or Django's ORM, but it does look like a good solution. I'll have to spend some time to learn it, though.

**Comment by surrealbytes** [comment]
[one possible solution for structuring the project](https://www.digitalocean.com/community/tutorials/how-to-structure-large-flask-applications)

**Comment by iodbh** [comment]
#25 Adds SQLAlchemy

Regarding project structure, Miguel Grinberk's [example app](https://github.com/miguelgrinberg/flasky/blob/master/flasky.py) is a neat model that's pretty standard.

I would also recommend not keeping the core app in `__main__.py`, as it partially break imports.

**Comment by surrealbytes** [comment]
That looks pretty nice, thank you! I will try and run the tests on this branch and see how it goes. Yeah everything should be moved out of `__main__.py` and into seperate modules, that was temporary.

**Comment by surrealbytes** [comment]
Okay i will have time this w/e to move stuff out `__main__.py`, i will built on top of #25  so not to create more conflicts. 

For a later stage I was thinking of ways to model the concept of konsent with classes that will not depend on flask and sqlalchemy to create a kind of state machine, but this will require some thought and discussion as per #24

also :heart: time heuristics

**Comment by iodbh** [comment]
I love the idea of the independent modeling. If we can build a decent abstraction with a simple integration layer, that would also allow us to add different consensus models from which each community could choose. Cool stuff.

**Comment by surrealbytes** [comment]
So i haven't done much that deserves a PR, been reading mostly about Flask and drinking beer the rest of the time :smile: A start would be to move everything from `__main__.py` to `__init__.py` but we can do better.

Apparently Flask is a little beast, i am not sure what's the best approach to decouple things. There are
[Blueprints](http://flask.pocoo.org/docs/0.12/blueprints/#why-blueprints) but there are also [Views](http://flask.pocoo.org/docs/0.12/views/), not idea how they fit together yet. Anyways i think i will start with unit testing and fixing #28 before attempting to move code around.

**Comment by iodbh** [comment]
Miguel Grinberg is pretty much the reference when it comes to Flask, if you haven't stumbled upon that yet check his [book](https://flaskbook.com/#) or ["mega-tutorial"](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world). I usually use his example app structure for flask projects.

When it comes to decoupling, I find the blueprints interface much more comfortable to work with.

**Comment by dellitsni** [comment]
Can confirm what @iodbh is saying, blueprints is a neat interface. I haven't played much with views, though.

> that would also allow us to add different consensus models from which each community could choose

That'd be really neat.

**Comment by dellitsni** [comment]
Closed by accident, I'm a little tired...
