### ISSUE TITLE
sqlalchemy.exc.IntegrityError Duplicate entry for key 'username'

### ISSUE THREAD

**Issue by surrealbytes** [dellitsni/Konsent#34]
sqlalchemy.exc.IntegrityError: (_mysql_exceptions.IntegrityError) (1062, "Duplicate entry 'test_username' for key 'username'") [SQL: 'INSERT INTO users (password, username, authority, union_id) VALUES (%s, %s, %s, %s)'] [parameters: ('cc246a15ad402a7483b435d05f2a954c12bb3a84d87555cd0e68806488516f92', 'test_username', 0, 1)] (Background on this error at: http://sqlalche.me/e/gkpj)

happens when trying to create a user with the same credentials,
can anyone reproduce?

**Comment by dellitsni** [comment]
I'm getting the same error. Happens because the `username` field is set to be unique in the database. We should check if the username exists already before trying to insert it, and throw a proper "username is taken" error if it already exists.
