### ISSUE TITLE
We've almost closed every issue in the v. 0.2a milestone

### ISSUE THREAD

**Issue by dellitsni** [dellitsni/Konsent#37]
Looks like we're almost ready to merge develop into master, just one more issue left in the milestone, #11. Is there anything we should add to the milestone?

**Comment by surrealbytes** [comment]
https://github.com/dellitsni/Konsent/pull/32#issuecomment-377792385

btw do you want to have the master branch as the develop branch and do releases with git tags? 
that's what most projects do but i don't mind really.

**Comment by surrealbytes** [comment]
the problem is this line, password has to be String or binary
```
models.py
105     password = db.Column(db.Unicode(length=255), nullable=False)
```

**Comment by dellitsni** [comment]
Strange, everything seemed to work before i merged. Travelling through Germany in a tight-packed train at the moment, I'll take a look at it as soon as i can!

**Comment by dellitsni** [comment]
Now that that is fixed.. How about we remove #11 from the milestone so @UnbanTwin can finish it if they want to, then we'll do some final testing and merge everything into master?

I actually really like this branch structure, if you don't mind i think we should keep it this way.

**Comment by dellitsni** [comment]
I added a changelog section to the readme, probably missed a few things though.

**Comment by surrealbytes** [comment]
you have to install konsent. i use a virtualenv and install in develop mode.

**Comment by dellitsni** [comment]
Alright, never dealt with that approach before but if you have experience with it then i suppose it works!

**Comment by surrealbytes** [comment]
http://flask.pocoo.org/docs/0.12/server/

Armin, the creator of Flask recommends this way, i think he knows something :smile: 

anyway, most of the projects out there usually require installation even in develop mode,
that's why pip has the `-e` option. in the project's root dir do a `pip install -e .`

**Comment by dellitsni** [comment]
Merged develop into master.
