### ISSUE TITLE
Implement CSRF protection

### ISSUE THREAD

**Issue by dellitsni** [dellitsni/Konsent#4]
There's currently no protection against cross-site request forgery. It's pretty simple to implement, and shouldn't be much of an issue.

**Comment by surrealbytes** [comment]
`wtforms` seems to implement something for CSRF but i've never used the library before.

**Comment by dellitsni** [comment]
@surrealbytes That's right, the documentation for CSRF Protection in WTForms can be found [here](https://wtforms.readthedocs.io/en/latest/csrf.html). I'll read it through when i get the time, seems like it's easy enough to implement.

**Comment by dellitsni** [comment]
Done.

**Comment by surrealbytes** [comment]
thank you!
