### ISSUE TITLE
Phases update is not consistent

### ISSUE THREAD

**Issue by surrealbytes** [dellitsni/Konsent#51]
At the moment updating the phases is something that happens only on requests and not automatically, meaning that some issues will stay in a phase, even though the time has passed, until someone requests
a view.

**Comment by dellitsni** [comment]
I've been thinking some about this, can't really figure out a clean way to do it besides using something external like cron. Do you have anything in mind?

**Comment by surrealbytes** [comment]
a timer in a thread :( 

i will look more into this

**Comment by dellitsni** [comment]
I've tried some different approaches to timers, but they were clunky, resource-heavy and error-prone. I didn't look enough, admittedly, so there might be good multi-threading solutions.
