### ISSUE TITLE
Add testing

### ISSUE THREAD

**Issue by surrealbytes** [dellitsni/Konsent#6]
Hello! pytest is my goto testing framework but this can happen with the builtin `unittest` module too, any preference? [selenium](https://github.com/SeleniumHQ/selenium) can also help for testing webapps

**Comment by dellitsni** [comment]
@surrealbytes I know my way around Selenium, but it seems like overkill. It'd be nice if we could use `unittest` since it's built-in.

**Comment by surrealbytes** [comment]
at this point we can write integration tests and selenium makes it very easy.
have you worked with pytest before? is way more pythonic than the builtin `unittest`,
you just use `assert` for your tests, no ugly named methods. I have already some basic boilerplate code using pytest and selenium, TDD ftw.

**Comment by dellitsni** [comment]
@surrealbytes Never worked with pytest before, but it looks pretty neat. Seems like the best option, even better if you've worked with it before.
