### ISSUE TITLE
Pythoneverywhere not progressing issues

### ISSUE THREAD

**Issue by surrealbytes** [dellitsni/Konsent#63]
This seems to be a pythoneverywhere problem indeed,  locally this works as expected. 
Maybe we should add some logging to the `update_phases` and see what pythoneverwhere's console prints?

**Comment by surrealbytes** [comment]
@dellitsni i've made a matrix room at konsent:matrix.org so we can have a more realtime conversation about stuff.

**Comment by dellitsni** [comment]
Can't find your matrix room.

**Comment by surrealbytes** [comment]
oops i've made the room private, which is the default, not so familiar with matrix/riot yet.
i've invited you
