### ISSUE TITLE
Newly created issue has 24-hour-ago timestamp

### ISSUE THREAD

**Issue by DarkerStar** [dellitsni/Konsent#73]
When I created my first issue, the "your post have been published" page showed that my issue was 23h 59min old (*immediately* after creation). See attached screenshot.

![konsent-new-issue-time-bug-screenshot](https://user-images.githubusercontent.com/2659436/39149858-7f63dd6e-470e-11e8-86ca-4358919138f9.png)

The problem seemed to go away after refresh, and the time showed correctly.

**Comment by surrealbytes** [comment]
my regression for sure, will get on it, thanks for reporting!

**Comment by DarkerStar** [comment]
If it's *never* happening on a local instance, it may be an artifact of network delays. I could create another issue on the live site to see if it happens again?

**Comment by surrealbytes** [comment]
you can go ahead and test w/e you want. expect konsent to change a lot and probably the database will get wiped some times until we are stable enough.

i've created 2 issues to test this on PA, it happened only on one

**Comment by dellitsni** [comment]
I remember seeing this on earlier local versions too, I don't think it's got anything to do with the hosting. I'll see if i can reproduce later.

**Comment by DarkerStar** [comment]
Ah, okay, if you can reproduce it, that's fine then. It just sounded like you weren't able to reproduce it.

**Comment by surrealbytes** [comment]
i still can't reproduce it locally and it sometimes doesn't happen on PA as well.

**Comment by surrealbytes** [comment]
i think i found where the bugs is, it boils down to `datetime.now() - datetime.now()` which is nasty

**Comment by surrealbytes** [comment]
#80

**Comment by dellitsni** [comment]
Fixed.
